# Generated by Django 5.2.11 on 2026-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"organization"."coordinaciones"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Divisiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"organization"."divisiones"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gerencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"organization"."gerencias"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaGerencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"organization"."persona_gerencia"',
                'managed': False,
            },
        ),
    ]
