# Generated by Django 5.2.11 on 2026-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cupo_total', models.IntegerField(blank=True, null=True)),
                ('cupo_disp', models.IntegerField(blank=True, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"appointments"."agenda"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('first_time', models.BooleanField(default=False)),
                ('fecha_hora_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"appointments"."cita_medica"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorAgenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"appointments"."doctor_agenda"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"appointments"."documentos"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenciaMedica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_referencia', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_create', models.DateField(blank=True, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"appointments"."referencia_medica"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vitales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tension_arterial', models.CharField(blank=True, max_length=255, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"appointments"."vitales"',
                'managed': False,
            },
        ),
    ]
