# Generated by Django 5.2.11 on 2026-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad_lote', models.IntegerField(blank=True, null=True)),
                ('cantidad_actual', models.IntegerField(blank=True, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"inventory"."lote"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicamentoLote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"inventory"."medicamento_lote"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('concentracion', models.CharField(blank=True, max_length=255, null=True)),
                ('forma_farmaceutica', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"inventory"."medicamentos"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoBeneficios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '"inventory"."movimiento_beneficios"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"inventory"."movimiento_cita"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoLote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"inventory"."movimiento_lote"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipioActivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"inventory"."principio_activo"',
                'managed': False,
            },
        ),
    ]
