# Generated by Django 5.2.11 on 2026-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentacionP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."alimentacion_p"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesAlergia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sustancia', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_reaccion', models.CharField(blank=True, max_length=255, null=True)),
                ('gravedad', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."antecedentes_alergia"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesgDescrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."antecedentesg_descrip"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesGenerales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alergias', models.BooleanField(default=False)),
                ('medicamentos_habituales', models.BooleanField(default=False)),
                ('antecedentes_quirurgicos', models.BooleanField(default=False)),
                ('apf', models.BooleanField(default=False)),
                ('apnp', models.BooleanField(default=False)),
                ('app', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"medical_history"."antecedentes_generales"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesGinecologia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edad_menarquia', models.IntegerField(blank=True, null=True)),
                ('ciclo_regular', models.IntegerField(blank=True, null=True)),
                ('fum', models.DateField(blank=True, null=True)),
                ('dismenorrea', models.BooleanField(default=False)),
                ('sangrado_anormal', models.BooleanField(default=False)),
                ('metodo_anticonceptivo', models.TextField(blank=True, null=True)),
                ('its', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."antecedentes_ginecologia"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesGinecoObstetrico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gestas', models.BooleanField(default=False)),
                ('partos', models.BooleanField(default=False)),
                ('cesareas', models.BooleanField(default=False)),
                ('abortos', models.BooleanField(default=False)),
                ('hijos', models.IntegerField(blank=True, null=True)),
                ('ectopicos', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."antecedentes_gineco_obstetrico"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesMedicamentosh',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(blank=True, max_length=255, null=True)),
                ('dosis', models.CharField(blank=True, max_length=255, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."antecedentes_medicamentosh"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentespDescrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."antecedentesp_descrip"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesPediatricos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('a_prenatal', models.BooleanField(default=False)),
                ('a_perinatales', models.BooleanField(default=False)),
                ('a_postnatales', models.BooleanField(default=False)),
                ('a_vacunas', models.BooleanField(default=False)),
                ('alimentacion_p', models.BooleanField(default=False)),
                ('desarrollo_p', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"medical_history"."antecedentes_pediatricos"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesSaludmental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appp', models.BooleanField(default=False)),
                ('appf', models.BooleanField(default=False)),
                ('habitos_p', models.BooleanField(default=False)),
                ('historia_biopatog', models.BooleanField(default=False)),
                ('genitograma', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"medical_history"."antecedentes_saludmental"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='APerinatales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edad_gestacional', models.IntegerField(blank=True, null=True)),
                ('apgar_1', models.IntegerField(blank=True, null=True)),
                ('apgar_5', models.IntegerField(blank=True, null=True)),
                ('peso_nacer', models.IntegerField(blank=True, null=True)),
                ('talla_nacer', models.IntegerField(blank=True, null=True)),
                ('complicaciones', models.TextField(blank=True, null=True)),
                ('hospitalizacion', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."a_perinatales"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='APostnatales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('gravedad', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('hospitalizacion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"medical_history"."a_postnatales"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='APrenatal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('control_prenatal', models.IntegerField(blank=True, null=True)),
                ('enfermedades_maternas', models.TextField(blank=True, null=True)),
                ('infecciones', models.TextField(blank=True, null=True)),
                ('consumos_sustancias', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."a_prenatal"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AVacunas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dosis', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_aplicacion', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"medical_history"."a_vacunas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitasLab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('inter_extern', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."citas_lab"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesarrolloP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edad_meses', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."desarrollo_p"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ecosonografico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_cita', models.IntegerField(blank=True, null=True)),
                ('transductor_convex', models.BooleanField(default=False)),
                ('transductor_transvaginal', models.BooleanField(default=False)),
                ('vejiga_llena', models.BooleanField(default=False)),
                ('vejiga_normal', models.BooleanField(default=False)),
                ('utero_posicion', models.IntegerField(blank=True, null=True)),
                ('utero_forma', models.IntegerField(blank=True, null=True)),
                ('utero_borde', models.IntegerField(blank=True, null=True)),
                ('patron_miometrial', models.IntegerField(blank=True, null=True)),
                ('utero_longitud', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('utero_transverso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('utero_ap', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('endometrio_visible', models.BooleanField(default=False)),
                ('endometrio_continuo', models.BooleanField(default=False)),
                ('endometrio_homogeneo', models.BooleanField(default=False)),
                ('cavidad_estado', models.BooleanField(default=False)),
                ('cavidad_espesor', models.CharField(blank=True, max_length=255, null=True)),
                ('otros_hallazgos', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('conclusiones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."ecosonografico"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventosObstetrico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('semana_gestacion', models.IntegerField(blank=True, null=True)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('complicaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."eventos_obstetrico"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('lab', models.BooleanField(default=False)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."examenes"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genitograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."genitograma"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaBiopatografica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."historia_biopatografica"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaMedica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('examen_fisico', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('examenes_solicitados', models.TextField(blank=True, null=True)),
                ('interconsulta', models.IntegerField(blank=True, null=True)),
                ('especialidad_interconsulta', models.TextField(blank=True, null=True)),
                ('exam_solic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."historia_medica"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Its',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('fecha_diagnostico', models.DateField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('tratam_prolongado', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('create_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."its"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NumHistoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_historia', models.IntegerField(blank=True, null=True)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."num_historia"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."odontograma"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OdontogramaDiente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pieza_dental', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."odontograma_diente"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ovarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ovario_lado', models.IntegerField(blank=True, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('transversal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ap', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volumen', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': '"medical_history"."ovarios"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAntecedentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_antecedente', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."tipo_antecedentes"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoExamenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_history"."tipo_examenes"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': '"medical_history"."vacunas"',
                'managed': False,
            },
        ),
    ]
