# Generated by Django 5.2.11 on 2026-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.IntegerField(blank=True, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"users"."familiares"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_persona', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"users"."personas"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('id_usucreate', models.IntegerField(blank=True, null=True)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('id_usupdate', models.IntegerField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"users"."usuarios"',
                'managed': False,
            },
        ),
    ]
