# Generated by Django 5.2.11 on 2026-02-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_link', to='users.personas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"users"."user_personas"',
            },
        ),
    ]
