# Generated by Django 5.2.11 on 2026-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_staff"."doctores"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.IntegerField(blank=True, null=True)),
                ('fecha_create', models.DateTimeField(blank=True, null=True)),
                ('fecha_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"medical_staff"."especialidades"',
                'managed': False,
            },
        ),
    ]
